### ISSUE TITLE
[feature suggestion] automatic timezone spoofing to match browser proxy configuration

### ISSUE THREAD

**Issue by n8v8R** [joue-quroi/spoof-timezone#1]
if feasible to be aware of brower's proxy ip and match the time zone automatically, for users frequently switching proxy endpoints

**Comment by joue-quroi** [comment]
Thanks for the suggestion! I added two new items:

1. There is a right-click context menu item to manually update the timezone based on your IP address
2. There is a new option in the settings page to update the timezone on browser restarts

There is no easy way to detect timezone changes automatically unless there is a periodic check which does not guarantee the immediate update. So the extension only checks on browser restarts if the option is enabled. At this point, it is the user responsibility to use the context menu item when the proxy configuration is changed while browsing.
