### ISSUE TITLE
v0.3.2 breaks certain websites

### ISSUE THREAD

**Issue by mvn23** [joue-quroi/spoof-timezone#28]
Since updating to v0.3.2 some websites don't show anymore. All I get is a blank page. The source is still loaded and viewable, but the page doesn't render at all.

Steps to reproduce:
* Have version 0.3.2 installed and enabled
* Try to load one of the affected websites (e.g. thingiverse.com)

Expected result: The website should be rendered.
Actual result: Only a blank page is shown.

If I disable the addon, all is working fine again.

**Comment by joue-quroi** [comment]
This website generates invalid dates for some reason, and that causes the issue. It is now fixed. Can you provide more websites? I like to test them before releasing the new version.

**Comment by mvn23** [comment]
So far I only found thingiverse and my octoprint instance. That happened to be the two websites I was working with when I noticed the issue. If I find any more I will post them here.
