### ISSUE TITLE
Instructions for contributing

### ISSUE THREAD

**Issue by themartorana** [joue-quroi/spoof-timezone#5]
I'd love to hack on #4 and submit a PR, but I don't have much knowledge of how webext works, or why you have a soft-link checked into the repo. I know it's necessary because I tried to load it unpacked into Chrome and it complained of missing dependencies.

Thanks!

**Comment by xiegeo** [comment]
And a readme and license too.

@themartorana You can open the xpi file (at least for firefox) as a .zip, the webext files are in there.

**Comment by joue-quroi** [comment]
Sorry for my late reply. I wasn't getting emails from GitHub! Okay so the webex dependency is removed and the license file is added. 

Contributions are welcomed! I am going to comment on #4.
