### ISSUE TITLE
Version 0.2.0 not working anymore on Firefox 61.0.1

### ISSUE THREAD

**Issue by Daisenki** [joue-quroi/spoof-timezone#7]
Hi,

the version 0.2.0 does not work anymore with Firefox 61.0.1, no setting change anything or spoof anything.

I test it with https://whoer.net/#extended

**Comment by joue-quroi** [comment]
Can you confirm this on a clean profile?

**Comment by Daisenki** [comment]
I have test it now, it seems to be a problem with other addons on my Firefox. It works on a new profile. So I close the ticket.
