### ISSUE TITLE
option to preserve toString between browser restarts

### ISSUE THREAD

**Issue by n8v8R** [joue-quroi/spoof-timezone#8]
FF 61.0.1 (64-bit) with ST 0.2.2 on W10 1709 b16299.579 

Similar to #3 `toString ` is not preserved between browser restarts and needs to be set again on each browser start. That can be tedious at times.

**Comment by joue-quroi** [comment]
Mine keeps the settings as expected after a browser restart. Are you sure you don't have the update from IP address setting enabled?

**Comment by n8v8R** [comment]
`Automatically update timezone based on my IP` is unchecked/disabled.

Tried with a maiden profile and `toString` as well as the TZ set prior to the browser restart are preserved after browser restart.

Are those STZ settings retained via `local storage`? 

I am using a FF WE named `Cookie AutoDelete` with a setting enabled `Localstorage Cleanup` which would clean up the local storage at browser restart. It does not provide an option to be selective about local storage used by other WE and content recceived from the Web.
To my understanding that is the current design of the governing WE API for FF 61 but may change (protect local storage utilized by WE) in upcoming beta/nightly. If not mistaken I read something about it but cannot recall where right now.

If that is being the case than apparently STZ is working as intended and being impacted however by another WE and thus this ticket as well as #3 are obsolote and can be closed.

Cleaning Local Storage between broswer restarts would be the most obvious cause. Else I would not expect using containers and having FPI (First Party Isolation) enabled to be the cause.

**Comment by joue-quroi** [comment]
Firefox should to keep the localStroage for addons and delete page related storage area, like what Chrome does. Unfortunately there is no fix for this.
